/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavigationButton: typeof import('./src/components/Navigation/Button.vue')['default']
    NavigationMenu: typeof import('./src/components/Navigation/Menu.vue')['default']
    ProfileBar: typeof import('./src/components/profile/Bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UtilsDashboard: typeof import('./src/components/utils/Dashboard.vue')['default']
    UtilsFooter: typeof import('./src/components/utils/Footer.vue')['default']
    UtilsHeader: typeof import('./src/components/utils/Header.vue')['default']
  }
}

// For TSX support
declare global {
  const NavigationButton: typeof import('./src/components/Navigation/Button.vue')['default']
  const NavigationMenu: typeof import('./src/components/Navigation/Menu.vue')['default']
  const ProfileBar: typeof import('./src/components/profile/Bar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UtilsDashboard: typeof import('./src/components/utils/Dashboard.vue')['default']
  const UtilsFooter: typeof import('./src/components/utils/Footer.vue')['default']
  const UtilsHeader: typeof import('./src/components/utils/Header.vue')['default']
}