services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./backend/logs/db:/app/logs

    env_file:
      - .env

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
  
    image: kodeklubb_api
    depends_on:
      db:
        condition: service_healthy

    restart: always

    ports:
      - "5154:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    volumes:
      - ./backend/src:/src
      - ./backend/logs/api:/app/logs

volumes:
  postgres_data:
  pgadmin_data: